# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-25 02:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True, verbose_name='权限名称')),
                ('description', models.TextField(verbose_name='权限详情介绍')),
            ],
        ),
        migrations.CreateModel(
            name='Vip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, unique=True, verbose_name='VIP名称')),
                ('level', models.IntegerField(verbose_name='会员等级')),
                ('price', models.FloatField(verbose_name='会员价格')),
            ],
        ),
        migrations.CreateModel(
            name='VipPermRalation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vid', models.IntegerField(verbose_name='会员的ID')),
                ('pid', models.IntegerField(verbose_name='权限的ID')),
            ],
        ),
    ]
