# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-23 06:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid1', models.IntegerField(verbose_name='好友1的ID')),
                ('uid2', models.IntegerField(verbose_name='好友2的ID')),
            ],
        ),
        migrations.RenameField(
            model_name='swiped',
            old_name='time',
            new_name='stime',
        ),
        migrations.AlterField(
            model_name='swiped',
            name='flag',
            field=models.CharField(choices=[('dislike', '左滑'), ('superlike', '上滑'), ('like', '右滑')], max_length=16, verbose_name='滑动类型'),
        ),
    ]
