# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-23 06:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='max_dating_age',
            field=models.IntegerField(default=50, verbose_name='最大交友年龄'),
        ),
    ]
